static_site:
  name: my_portfolio_frontend   # match your Render service name
  root: frontend                # where your Vite code lives
  buildCommand: npm install && npm run build
  publishPath: dist
  routes:
    - type: rewrite
      source:  /<*>
      destination: /index.html