# render.yaml
services:
  - type: staticSite
    name: my_portfolio_frontend   # must match your Render service name
    env: node
    branch: main
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source:  "/<*>"
        destination: "/index.html"
